# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: chill

  auto_review:
    enabled: true

  high_level_summary: false
  walkthrough: false
  poem: true
  fortune: false
  progress_updates: false

tone:
  emojis: false
  style: professional